### ISSUE TITLE
Rare unhandled exception 'monaco not defined'

### ISSUE THREAD

**Issue by svenboulanger** [serdarciplak/BlazorMonaco#18]
With a minimal implementation of the editor it is possible to create an unhandled exception by refreshing without caching (CTRL+F5 in Chrome).

For this, I created an empty Blazor webassembly project, and just inserted an empty editor in the index. I then press CTRL+F5 a few times and every once in a while, you can see the following stack trace in the console:

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: monaco is not defined
      ReferenceError: monaco is not defined
          at Object.create (https://localhost:44373/_content/BlazorMonaco/jsInterop.js:39:22)
          at https://localhost:44373/_framework/blazor.webassembly.js:1:9805
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44373/_framework/blazor.webassembly.js:1:9773)
          at _mono_wasm_invoke_js_marshalled (https://localhost:44373/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
          at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
          at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[5109]:0xddb3d)
Microsoft.JSInterop.JSException: monaco is not defined
ReferenceError: monaco is not defined
    at Object.create (https://localhost:44373/_content/BlazorMonaco/jsInterop.js:39:22)
    at https://localhost:44373/_framework/blazor.webassembly.js:1:9805
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44373/_framework/blazor.webassembly.js:1:9773)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44373/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
    at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[5109]:0xddb3d)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2e21640 + 0x00034> in <filename unknown>:0 
  at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync (Microsoft.JSInterop.IJSRuntime jsRuntime, System.String identifier, System.Object[] args) <0x2dd4600 + 0x000e4> in <filename unknown>:0 
  at BlazorMonaco.MonacoEditorBase.Create (System.String id, BlazorMonaco.Bridge.StandaloneEditorConstructionOptions options) <0x2d135b0 + 0x0016c> in <filename unknown>:0 
  at BlazorMonaco.MonacoEditor.OnAfterRenderAsync (System.Boolean firstRender) <0x2d12a00 + 0x000fe> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2de2038 + 0x000b6> in <filename unknown>:0 
```

**Comment by svenboulanger** [comment]
I could trace the issue back to the order of the scripts in `index.html`. In your example, the Monaco scripts come before loading the webassembly script, while in mine it came after loading the `_framework/blazor.webassembly.js` script.

Please update this information in the README for others.

**Comment by serdarciplak** [comment]
Thanks for the info. I'm adding that clearification to the README.
